#define	BN_DEAL		101
#define	BN_EXIT		102
#define	BN_REMOVE	103
#define BN_RESET	104
#define	IDM_EXIT	201
#define	IDM_ABOUT	202
#define IDM_PREFERENCES 203
#define TB_DEALS	301
#define	TB_ERROR	302
#define TB_SUITS	303
#define TB_SUIT		304

#define SB_ROWS                     101
#define EB_ROWS                     102
#define SB_COLUMNS                  103
#define EB_COLUMNS                  104
#define BN_DEFAULTS                 109
